package com.example.sevilla.ui.theme
import androidx.compose.ui.graphics.Color

/**
 * Colores para el tema claro.
 */
val primaryLight = Color(0xFF8D4A5A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD9DF)
val onPrimaryContainerLight = Color(0xFF713343)
val secondaryLight = Color(0xFF75565C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFD9DF)
val onSecondaryContainerLight = Color(0xFF5B3F45)
val tertiaryLight = Color(0xFF7A5733)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDCBD)
val onTertiaryContainerLight = Color(0xFF60401D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF22191B)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF22191B)
val surfaceVariantLight = Color(0xFFF3DDE0)
val onSurfaceVariantLight = Color(0xFF524346)
val outlineLight = Color(0xFF847375)
val outlineVariantLight = Color(0xFFD6C2C4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E30)
val inverseOnSurfaceLight = Color(0xFFFEEDEE)
val inversePrimaryLight = Color(0xFFFFB1C2)
val surfaceDimLight = Color(0xFFE7D6D8)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F1)
val surfaceContainerLight = Color(0xFFFBEAEC)
val surfaceContainerHighLight = Color(0xFFF5E4E6)
val surfaceContainerHighestLight = Color(0xFFEFDEE0)

/**
 * Colores para el tema claro con contraste medio.
 */
val primaryLightMediumContrast = Color(0xFF5C2233)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF9E5869)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF492F34)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF85656B)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF4D300E)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF8B6640)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F7)
val onBackgroundLightMediumContrast = Color(0xFF22191B)
val surfaceLightMediumContrast = Color(0xFFFFF8F7)
val onSurfaceLightMediumContrast = Color(0xFF170F11)
val surfaceVariantLightMediumContrast = Color(0xFFF3DDE0)
val onSurfaceVariantLightMediumContrast = Color(0xFF403335)
val outlineLightMediumContrast = Color(0xFF5E4F51)
val outlineVariantLightMediumContrast = Color(0xFF79696C)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF382E30)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFEEDEE)
val inversePrimaryLightMediumContrast = Color(0xFFFFB1C2)
val surfaceDimLightMediumContrast = Color(0xFFD3C3C4)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F7)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF0F1)
val surfaceContainerLightMediumContrast = Color(0xFFF5E4E6)
val surfaceContainerHighLightMediumContrast = Color(0xFFEAD9DB)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDECED0)

/**
 * Colores para el tema claro con contraste alto.
 */
val primaryLightHighContrast = Color(0xFF501829)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF743545)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF3E252B)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF5E4147)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF412605)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF634220)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F7)
val onBackgroundLightHighContrast = Color(0xFF22191B)
val surfaceLightHighContrast = Color(0xFFFFF8F7)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF3DDE0)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF36292B)
val outlineVariantLightHighContrast = Color(0xFF544548)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF382E30)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFB1C2)
val surfaceDimLightHighContrast = Color(0xFFC4B5B7)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F7)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFEEDEE)
val surfaceContainerLightHighContrast = Color(0xFFEFDEE0)
val surfaceContainerHighLightHighContrast = Color(0xFFE1D0D2)
val surfaceContainerHighestLightHighContrast = Color(0xFFD3C3C4)

/**
 * Colores para el tema oscuro.
 */
val primaryDark = Color(0xFFFFB1C2)
val onPrimaryDark = Color(0xFF551D2D)
val primaryContainerDark = Color(0xFF713343)
val onPrimaryContainerDark = Color(0xFFFFD9DF)
val secondaryDark = Color(0xFFE4BDC3)
val onSecondaryDark = Color(0xFF43292F)
val secondaryContainerDark = Color(0xFF5B3F45)
val onSecondaryContainerDark = Color(0xFFFFD9DF)
val tertiaryDark = Color(0xFFECBE91)
val onTertiaryDark = Color(0xFF462A09)
val tertiaryContainerDark = Color(0xFF60401D)
val onTertiaryContainerDark = Color(0xFFFFDCBD)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191113)
val onBackgroundDark = Color(0xFFEFDEE0)
val surfaceDark = Color(0xFF191113)
val onSurfaceDark = Color(0xFFEFDEE0)
val surfaceVariantDark = Color(0xFF524346)
val onSurfaceVariantDark = Color(0xFFD6C2C4)
val outlineDark = Color(0xFF9E8C8F)
val outlineVariantDark = Color(0xFF524346)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFDEE0)
val inverseOnSurfaceDark = Color(0xFF382E30)
val inversePrimaryDark = Color(0xFF8D4A5A)
val surfaceDimDark = Color(0xFF191113)
val surfaceBrightDark = Color(0xFF413738)
val surfaceContainerLowestDark = Color(0xFF140C0E)
val surfaceContainerLowDark = Color(0xFF22191B)
val surfaceContainerDark = Color(0xFF261D1F)
val surfaceContainerHighDark = Color(0xFF312829)
val surfaceContainerHighestDark = Color(0xFF3C3234)

/**
 * Colores para el tema oscuro con contraste medio.
 */
val primaryDarkMediumContrast = Color(0xFFFFD1D9)
val onPrimaryDarkMediumContrast = Color(0xFF481222)
val primaryContainerDarkMediumContrast = Color(0xFFC87A8C)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFBD2D9)
val onSecondaryDarkMediumContrast = Color(0xFF371F24)
val secondaryContainerDarkMediumContrast = Color(0xFFAB888E)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFD5AD)
val onTertiaryDarkMediumContrast = Color(0xFF3A2002)
val tertiaryContainerDarkMediumContrast = Color(0xFFB28960)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF191113)
val onBackgroundDarkMediumContrast = Color(0xFFEFDEE0)
val surfaceDarkMediumContrast = Color(0xFF191113)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF524346)
val onSurfaceVariantDarkMediumContrast = Color(0xFFEDD7DA)
val outlineDarkMediumContrast = Color(0xFFC1ADB0)
val outlineVariantDarkMediumContrast = Color(0xFF9E8C8F)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFEFDEE0)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF312829)
val inversePrimaryDarkMediumContrast = Color(0xFF723444)
val surfaceDimDarkMediumContrast = Color(0xFF191113)
val surfaceBrightDarkMediumContrast = Color(0xFF4D4243)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0607)
val surfaceContainerLowDarkMediumContrast = Color(0xFF241B1D)
val surfaceContainerDarkMediumContrast = Color(0xFF2F2527)
val surfaceContainerHighDarkMediumContrast = Color(0xFF3A3032)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF463B3D)

/**
 * Colores para el tema oscuro con contraste alto.
 */
val primaryDarkHighContrast = Color(0xFFFFEBEE)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFABBD)
val onPrimaryContainerDarkHighContrast = Color(0xFF210009)
val secondaryDarkHighContrast = Color(0xFFFFEBEE)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFE0B9C0)
val onSecondaryContainerDarkHighContrast = Color(0xFF18060A)
val tertiaryDarkHighContrast = Color(0xFFFFEDDE)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFE8BA8D)
val onTertiaryContainerDarkHighContrast = Color(0xFF150800)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF191113)
val onBackgroundDarkHighContrast = Color(0xFFEFDEE0)
val surfaceDarkHighContrast = Color(0xFF191113)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF524346)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFFFEBEE)
val outlineVariantDarkHighContrast = Color(0xFFD2BEC0)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEFDEE0)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF723444)
val surfaceDimDarkHighContrast = Color(0xFF191113)
val surfaceBrightDarkHighContrast = Color(0xFF594D4F)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF261D1F)
val surfaceContainerDarkHighContrast = Color(0xFF382E30)
val surfaceContainerHighDarkHighContrast = Color(0xFF43393A)
val surfaceContainerHighestDarkHighContrast = Color(0xFF4F4446)







